# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AirshipSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks


  # Pods for AirshipSample
  pod 'UrbanAirship-iOS-SDK', '~>8.3.0'


end
