platform :ios, '11.0'

require_relative "../../node_modules/react-native/scripts/react_native_pods"
require_relative "../../node_modules/@react-native-community/cli-platform-ios/native_modules"


target 'AirshipSample' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])
  use_native_modules!
end

target 'ServiceExtension' do
  platform :ios, '11.0'
  # Pods for Service Extension
  pod 'AirshipExtensions/NotificationService', '~> 14.3.0'
end

# https://github.com/software-mansion/react-native-screens/issues/842
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNScreens')
      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end
end
