use_frameworks!
platform :ios, '11.0'
$node_modules_path = '../../node_modules'

require_relative "#{$node_modules_path}/react-native/scripts/react_native_pods"
require_relative "#{$node_modules_path}/@react-native-community/cli-platform-ios/native_modules"

target 'AirshipSample' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

target 'ServiceExtension' do
  platform :ios, '11.0'
  # Pods for Service Extension
  pod 'AirshipExtensions/NotificationService'
end
